import {
  EventSettings,
  Partner,
  PracticalInfo,
  ProgramSession,
  Speaker,
  Participant,
} from "./types";

export const mockEventSettings: EventSettings = {
  id: "mock",
  event_name: "Convention JCI Niger 2026",
  tagline: "Votre Convention. Votre expérience. Votre réseau.",
  hashtag: "#MaConventionJCI2026",
  start_date: "2026-10-09",
  end_date: "2026-10-10",
  location: "Maradi, Niger",
  hero_text:
    "Retrouvez tout ce dont vous avez besoin pour vivre pleinement la Convention JCI Niger 2026.",
  logo_url: null,
  secondary_logo_url: null,
  color_primary: "#130F2D",
  color_accent: "#0097D7",
  social_facebook: null,
  social_instagram: null,
  social_linkedin: null,
  social_whatsapp: null,
};

export const mockSpeakers: Speaker[] = [
  {
    id: "sp-1",
    name: "Aïcha Moussa",
    photo_url: null,
    position: "Présidente Nationale",
    organization: "JCI Niger",
    bio: "Aïcha porte la vision nationale de JCI Niger et accompagne les Locaux dans le développement du leadership des jeunes à travers le pays.",
    display_order: 1,
    is_visible: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "sp-2",
    name: "Ibrahim Saley",
    photo_url: null,
    position: "Entrepreneur & Consultant",
    organization: "Sahel Ventures",
    bio: "Ibrahim accompagne les jeunes entrepreneurs nigériens depuis plus de dix ans, avec un focus sur l'agro-industrie et le financement des PME.",
    display_order: 2,
    is_visible: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "sp-3",
    name: "Fatouma Idé",
    photo_url: null,
    position: "Directrice Exécutive",
    organization: "Fondation Jeunesse Sahel",
    bio: "Fatouma travaille sur l'engagement civique des jeunes et le renforcement des compétences de leadership communautaire au Niger.",
    display_order: 3,
    is_visible: true,
    created_at: new Date().toISOString(),
  },
];

export const mockPartners: Partner[] = [
  {
    id: "pt-1",
    name: "Air Niger International",
    logo_url: null,
    category: "Partenaire officiel",
    description: "Partenaire aérien officiel de la Convention JCI Niger 2026.",
    website: "https://example.com",
    whatsapp: null,
    offer: "-15% sur les vols vers Maradi pour les participants.",
    display_order: 1,
    is_visible: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "pt-2",
    name: "Banque Sahel Finance",
    logo_url: null,
    category: "Partenaire principal",
    description: "Partenaire financier principal de la Convention.",
    website: "https://example.com",
    whatsapp: null,
    offer: null,
    display_order: 2,
    is_visible: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "pt-3",
    name: "Radio Ténéré",
    logo_url: null,
    category: "Partenaire média",
    description: "Couverture média officielle de l'événement.",
    website: null,
    whatsapp: "+22790000000",
    offer: null,
    display_order: 3,
    is_visible: true,
    created_at: new Date().toISOString(),
  },
];

export const mockProgram: ProgramSession[] = [
  {
    id: "pg-1",
    date: "2026-10-09",
    start_time: "08:00",
    end_time: "09:00",
    title: "Accueil & enregistrement",
    description: "Retrait des badges et installation des participants.",
    location: "Hall principal",
    category: "Cérémonie",
    speaker_id: null,
    display_order: 1,
    is_visible: true,
  },
  {
    id: "pg-2",
    date: "2026-10-09",
    start_time: "09:00",
    end_time: "10:30",
    title: "Cérémonie d'ouverture",
    description: "Ouverture officielle de la Convention JCI Niger 2026.",
    location: "Salle des Congrès",
    category: "Cérémonie",
    speaker_id: "sp-1",
    display_order: 2,
    is_visible: true,
  },
  {
    id: "pg-3",
    date: "2026-10-09",
    start_time: "10:30",
    end_time: "12:30",
    title: "Panel : Leadership et entrepreneuriat au Sahel",
    description: "Échanges avec des leaders nigériens sur l'entrepreneuriat.",
    location: "Salle des Congrès",
    category: "Panel",
    speaker_id: "sp-2",
    display_order: 3,
    is_visible: true,
  },
  {
    id: "pg-4",
    date: "2026-10-09",
    start_time: "12:30",
    end_time: "14:00",
    title: "Pause déjeuner",
    description: null,
    location: "Espace restauration",
    category: "Pause",
    speaker_id: null,
    display_order: 4,
    is_visible: true,
  },
  {
    id: "pg-5",
    date: "2026-10-09",
    start_time: "14:00",
    end_time: "16:00",
    title: "Formation : Prise de parole en public",
    description: null,
    location: "Salle B",
    category: "Formation",
    speaker_id: "sp-3",
    display_order: 5,
    is_visible: true,
  },
  {
    id: "pg-6",
    date: "2026-10-09",
    start_time: "16:00",
    end_time: "18:00",
    title: "Networking",
    description: "Moment d'échange entre participants et partenaires.",
    location: "Jardin extérieur",
    category: "Networking",
    speaker_id: null,
    display_order: 6,
    is_visible: true,
  },
  {
    id: "pg-7",
    date: "2026-10-10",
    start_time: "09:00",
    end_time: "12:00",
    title: "Assemblée statutaire",
    description: "Temps statutaire réservé aux membres JCI.",
    location: "Salle des Congrès",
    category: "Statutaire",
    speaker_id: null,
    display_order: 7,
    is_visible: true,
  },
  {
    id: "pg-8",
    date: "2026-10-10",
    start_time: "20:00",
    end_time: "23:00",
    title: "Soirée de clôture",
    description: "Gala de clôture de la Convention.",
    location: "Esplanade centrale",
    category: "Soirée",
    speaker_id: null,
    display_order: 8,
    is_visible: true,
  },
];

export const mockPracticalInfo: PracticalInfo[] = [
  {
    id: "pi-1",
    section: "Lieu",
    title: "Lieu de la Convention",
    content: "Palais des Congrès de Maradi, Niger.",
    map_url: "https://maps.google.com/?q=Maradi+Niger",
    display_order: 1,
    is_visible: true,
  },
  {
    id: "pi-2",
    section: "Hébergement",
    title: "Où loger à Maradi",
    content:
      "Une liste d'hôtels partenaires proposant des tarifs préférentiels sera communiquée aux participants inscrits.",
    map_url: null,
    display_order: 2,
    is_visible: true,
  },
  {
    id: "pi-3",
    section: "Transport",
    title: "Se déplacer à Maradi",
    content:
      "Des navettes seront organisées entre les points d'hébergement principaux et le lieu de la Convention.",
    map_url: null,
    display_order: 3,
    is_visible: true,
  },
  {
    id: "pi-4",
    section: "Restauration",
    title: "Repas",
    content:
      "Les pauses café et déjeuners sont inclus pour les participants inscrits les deux jours.",
    map_url: null,
    display_order: 4,
    is_visible: true,
  },
  {
    id: "pi-5",
    section: "Contacts utiles",
    title: "Contacts de l'organisation",
    content: "Comité d'organisation : contact@jci-niger.org · +227 90 00 00 00",
    map_url: null,
    display_order: 5,
    is_visible: true,
  },
  {
    id: "pi-6",
    section: "Informations importantes",
    title: "À prévoir",
    content:
      "Pensez à apporter une pièce d'identité pour le retrait de votre badge sur place.",
    map_url: null,
    display_order: 6,
    is_visible: true,
  },
];

export const mockParticipants: Participant[] = [
  {
    id: "pa-1",
    name: "Mariama Souley",
    city: "Niamey",
    organization: "JCI Niamey",
    role: "Déléguée",
    photo_url: null,
    is_public: true,
    phone: "+22790000001",
    member_code: "JCI-2026-CVGC",
    created_at: new Date().toISOString(),
  },
  {
    id: "pa-2",
    name: "Abdoul Kader Issa",
    city: "Zinder",
    organization: "JCI Zinder",
    role: "Membre JCI",
    photo_url: null,
    is_public: true,
    phone: "+22790000002",
    member_code: "JCI-2026-Z64K",
    created_at: new Date().toISOString(),
  },
  {
    id: "pa-3",
    name: "Halima Boubacar",
    city: "Maradi",
    organization: "JCI Maradi",
    role: "Organisatrice",
    photo_url: null,
    is_public: true,
    phone: "+22790000003",
    member_code: "JCI-2026-UHKC",
    created_at: new Date().toISOString(),
  },
];

export const mockStats = {
  participants: 340,
  posters: 512,
  badges: 298,
  partners: mockPartners.length,
};
